// All actions are declared here

const GET_USER_PROFILE = 'GET_USER_PROFILE'
const SET_USER_IN_REDUX = 'SET_USER_IN_REDUX'
const SET_USER_REQUEST_TYPE = 'SET_USER_REQUEST_TYPE'
const GET_USER_REQUEST_TYPE = 'GET_USER_REQUEST_TYPE'


export {
    SET_USER_IN_REDUX,
    GET_USER_PROFILE,
    SET_USER_REQUEST_TYPE,
    GET_USER_REQUEST_TYPE
}


